### ISSUE TITLE
声谱图

### ISSUE THREAD

**Issue by AriesJin** [huanghao128/tensorflow-mfcc#1]
您好，有些关于声谱图的问题想咨询一下您，方便加个微信吗？18860016532，期待您的回复

**Comment by huanghao128** [comment]
> 您好，有些关于声谱图的问题想咨询一下您，方便加个微信吗？18860016532，期待您的回复

其实我也不太懂，不是搞语音方向，只是需要用到，简单看了一下。。。

**Comment by AriesJin** [comment]
那么请问代码里面get_audio_data是用来干嘛的

**Comment by huanghao128** [comment]
> 那么请问代码里面get_audio_data是用来干嘛的
read_wav_data是直接读取音频wav格式文件，get_audio_data是读取已经提取好的音频时序数据，存在文本文件中，这两种读取方法是根据自己的数据选一种就可以了。

**Comment by huanghao128** [comment]
> 那么请问代码里面get_audio_data是用来干嘛的

read_wav_data是直接读取音频wav格式文件，get_audio_data是读取已经提取好的音频时序数据，存在文本文件中，这两种读取方法是根据自己的数据选一种就可以了。
